/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    NavBarComponent: typeof import('./src/components/NavBarComponent.vue')['default']
    RecipeComponent: typeof import('./src/components/RecipeComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmitRecipeFormComponent: typeof import('./src/components/SubmitRecipeFormComponent.vue')['default']
  }
}
