/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/favorites': RouteRecordInfo<'/favorites', '/favorites', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/myRecipes': RouteRecordInfo<'/myRecipes', '/myRecipes', Record<never, never>, Record<never, never>>,
    '/recipes/': RouteRecordInfo<'/recipes/', '/recipes', Record<never, never>, Record<never, never>>,
    '/recipes/[id]': RouteRecordInfo<'/recipes/[id]', '/recipes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/recipesSubmit': RouteRecordInfo<'/recipesSubmit', '/recipesSubmit', Record<never, never>, Record<never, never>>,
    '/recipeUpdate/': RouteRecordInfo<'/recipeUpdate/', '/recipeUpdate', Record<never, never>, Record<never, never>>,
    '/recipeUpdate/[id]': RouteRecordInfo<'/recipeUpdate/[id]', '/recipeUpdate/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
